name: CI-front

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Dependencies
      working-directory: ./
      run: yarn install
      
    - name: Build ReactJS
      env:
        CI: false
      working-directory: ./
      run: yarn run build
      
    - name: Login to DockerHub
      uses: docker/login-action@v1.8.0
      with:
        username: ${{ secrets.DOCKERHUB_FRONT_USERNAME }}
        password: ${{ secrets.DOCKERHUB_FRONT_TOKEN }}
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.4.0
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_FRONT_USERNAME }}/front:latest
